### ISSUE TITLE
Request help about running SWu-IKEv2 with srsRAN

### ISSUE THREAD

**Issue by WingPig99** [fasferraz/SWu-IKEv2#10]
Hi, Fasferra. I’m trying to run this project with EE, however, I encounter a problem when running `sudo python swu_emulator.py -m 0 -a tun_srsue -d 109.249.180.0`:
```
sending IKE_SA_AUTH (2)
received decoded message:
[[46, [[48, [4, 2]], [41, [1, 24, b'', b'']]]]]
received IKE_AUTH (2)
OTHER_ERROR : EAP FAILURE
```

`tun_srsue` is the interface created by [srsRAN](https://github.com/srsran/srsRAN).

Could you kindly give me some idea to solve it?

Thanks

**Comment by fasferraz** [comment]
Hi, you don't need to specify the IMSI, APN or MCC/MNC of the operator? If you don't specify, the default values are used.

**Comment by fasferraz** [comment]
Explanation of the values:
41 - Notify
24 - Authentication Failure 

Can you put here the complete log output?

**Comment by WingPig99** [comment]
Thanks for your reply. I have tried `sudo python swu_emulator.py -m 0 -a internet -d 109.249.180.0 --mnc 030 --mcc 234 --imsi 234304188171083`, but still the same problem.

Have sent the log and trace to your Gmail since it contains sensitive info.

**Comment by WingPig99** [comment]
Thanks for your kindly help. The problem is solved after I changed the APN to `IMS`. Following is the command.
```
sudo python swu_emulator.py -m 0 -a ims -d epdg.epc.mnc030.mcc234.pub.3gppnetwork.org --mnc 030 --mcc 234 --imsi XX
```
