### ISSUE TITLE
feature: put tun device in new network namespace

### ISSUE THREAD

**Issue by laf0rge** [fasferraz/SWu-IKEv2#7]
creating a separate network namespace for the tun device allows a clean separation of the traffic "inside" the tunnel [where normally the IMS client resides] and "outside" of the tunnel, i.e. the normal host IP stack.

Doing so also avoids having to add a host route to the ePDG, as the routing table of the host namespace is not modified.

I have implemented this in 3779d4967b6b6dc404e4552c741a2ec47da30418 and initial testing looks good.

**Comment by fasferraz** [comment]
I added that option based on your code, with some minor changes (to support dns also in namespaces).
I close this issue, since the feature is now implemented
