### ISSUE TITLE
AES 256 bits support?

### ISSUE THREAD

**Issue by phhusson** [fasferraz/SWu-IKEv2#9]
Hi,

First thanks for this project

It looks like there is some issue with AES256 support at ISAKMP level.
The other side refuses to negotiate `sa_list_child` part (not sure how it's called), and when looking at the decrypt in wireshark, wireshark doesn't understand the inner IKE_AUTH_MID and reports malformed packet.

I have one EPDG server on which I can connect with AES128 but not AES256. (and another one that requires AES256...)

What can I provide?

**Comment by phhusson** [comment]
Nevermind, I have a server on which I manage to connect as AES256. I'm doing something else wrong.
Sorry for the noise.

**Comment by fasferraz** [comment]
Hi,
So you were able to use AES256 with another ePDG, right?

**Comment by phhusson** [comment]
Yup, I managed to connect epdg.epc.mnc020.mcc208.pub.3gppnetwork.org with:

```
    sa_list = [                                                                                          
    [  
       [IKE,0],
       [ENCR,ENCR_AES_CBC,[KEY_LENGTH,256]],                                                             
       [PRF,PRF_HMAC_SHA2_256],
       [INTEG,AUTH_HMAC_SHA2_256_128],                                                                   
       [D_H,MODP_2048_bit]                                                                               
    ],
]

    sa_list_child = [
    [
        [ESP,4],
        [ENCR,ENCR_AES_CBC,[KEY_LENGTH,256]],
        [INTEG,AUTH_HMAC_SHA2_256_128],
        [ESN,ESN_NO_ESN]
    ] ,
]
```
